#!/bin/bash

jupyter contrib nbextension install --user
jupyter labextension install @oriolmirosa/jupyterlab_materialdarker
jupyter labextension enable jupyterlab_materialdarker
mkdir -p ~/.jupyterlab/user-settings/@jupyterlab/apputils-extension/ && echo '{"theme":"Material Darker" }' > themes.jupyterlab-settings
